name: checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_MAKE_RUN_CHECK_FORMAT: true
  CARGO_MAKE_RUN_CLIPPY: true
  RUST_LOG: debug

jobs:
  checks:
    name: Tests and clippy checks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Debug docker
        run: |
          echo "Docker version: $(docker version)"
          echo "Docker info: $(docker info)"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Run CI
        run: cargo make ci-flow
